### ISSUE TITLE
In some cases, barista loses group information after refresh (group dropdown / selection not available after login)

### ISSUE THREAD

**Issue by BarbaraCzub** [geneontology/noctua#569]
When I was making GO-CAM models, which I refer to in this annotation ticket https://github.com/geneontology/go-annotation/issues/2047, I was not able to select the ARUK-UCL attribution (or any other attribution). The drop-down menu with this option seems to have disappeared.  So now all of the models appear to be assigned by GO_Noctua (instead of ARUK-UCL).

cc @RLovering 

Here are the model details:

Test for AE and output comparison - case 1 gomodel:5b528b1100000699 | http://orcid.org/0000-0002-3898-1727 | development | 2018-08-07 |   |   |   |   | Edit Form GPAD OWL
-- | -- | -- | -- | -- | -- | -- | -- | --
Test for AE and output comparison - case 2 gomodel:5b528b1100000729 | http://orcid.org/0000-0002-3898-1727 | development | 2018-08-07 |   |   |   |   | Edit Form GPAD OWL
Test for AE and output comparison - case 3 gomodel:5b528b1100000667 | http://orcid.org/0000-0002-3898-1727 | development | 2018-08-07

**Comment by kltm** [comment]
Wow, that's weird. I can duplicate.
I'm looking into this now.

**Comment by kltm** [comment]
Refreshing has no effect (not that it should).
noctua-dev.berkeleybop.org still works as expected.
Will check server logs.

**Comment by kltm** [comment]
Possibly a supervisord restart attempt tried to bring up another barista, clobbering or making the running one unhappy?
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::9090
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1355:14)
    at listenInCluster (net.js:1396:12)
    at Server.listen (net.js:1480:7)
    at VantageServer.vantageServer.init (/home/swdev/local/src/git/noctua/node_modules/vantage/lib/server.js:130:17)
    at Vantage.listen (/home/swdev/local/src/git/noctua/node_modules/vantage/lib/index.js:160:17)
    at new BaristaLauncher (/home/swdev/local/src/git/noctua/barista.js:1311:10)
    at Object.<anonymous> (/home/swdev/local/src/git/noctua/barista.js:2656:15)
    at Module._compile (module.js:652:30)
[13:30:39] 'run-barista' errored after 865 ms
[13:30:39] Error: Command `node barista.js --debug 0 --users ~/local/src/git/go-site/metadata/users.yaml --groups ~/local/src/git/go-site/metadata/groups.yaml --self http://toaster.lbl.gov:3400 --secrets ~/local/src/git/go-internal/barista/ --context go --repl 9090` failed with exit code 1
    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by kltm** [comment]
Interesting that it was the local vantage server reporting there.

**Comment by kltm** [comment]
@BarbaraCzub I seem to have it working again. That was a little odd.
You may have to logout and login again. All of your work should be saved and fine.

**Comment by kltm** [comment]
Note that barista was reset, removing all current sessions and resetting temporary position information.

**Comment by pgaudet** [comment]
I think it has to do with the order in which your groups are listed in the users.yaml file. I dont know if something else needs to happen; can you please test again ? 

Thanks, Pascale

**Comment by BarbaraCzub** [comment]
So, while I'm working on a model, even if I select 'ARUK-UCL' to start with, if I need to refresh the page, it always reverts back to BHF-UCL.

**Comment by pgaudet** [comment]
Did you try logging out and log back in ?

**Comment by BarbaraCzub** [comment]
I have now. 'BHF-UCL' is still the default option.

**Comment by BarbaraCzub** [comment]
Maybe it could be removed completely from next to my name in the users.yaml file? 
(I do not expect I'll need to use it).

**Comment by pgaudet** [comment]
Sure - but still the order should be taken into account. I'd like to know what the issue is; perhaps this is not immediate.

**Comment by BarbaraCzub** [comment]
No, it's not immediate.

**Comment by kltm** [comment]
@pgaudet Note: https://github.com/geneontology/noctua/issues/456
As well, yes--there is always an extra manual step to make sure that problems do not leak into the system.

**Comment by kltm** [comment]
I'll put in to do the services restart later today.

**Comment by BarbaraCzub** [comment]
Thanks @kltm. My default group has now been updated.
