### ISSUE TITLE
Barista http-proxy service can time out on certain operations, crashing

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#60]
On some operations, the http proxy can crash like:

```
/home/sjcarbon/local/src/git/go-mme/node_modules/http-proxy/lib/http-proxy/index.js:114
    throw err;
          ^
Error: socket hang up
    at createHangUpError (http.js:1472:15)
    at Socket.socketCloseListener (http.js:1522:23)
    at Socket.emit (events.js:95:17)
    at TCP.close (net.js:465:12)
```

This is apparently known, but I'm still trying to find the exact origin in our case (or cases).

**Comment by kltm** [comment]
Me, and nobody else, has seen this in aaaages. I'm going to close for now.
