### ISSUE TITLE
Explore why Barista is having instability and restart issues

### ISSUE THREAD

**Issue by kltm** [geneontology/noctua#775]
Recently, barista has been crashing out completely, with little trace left in logs and little apparent complaint before it happened. As well, supervisord does not seem to be correctly rebooting the system.

Recent events:

2022-06-03 11:30:32
2022-05-23 12:32:51
2022-05-22 15:55:55
2022-04-26 10:01:09

This seems to be an uptick when compared to historical numbers. A theory is that this is either related to the imports (more larger models) or AGR widget (increased remote traffic). If correct, the latter would be addressed by https://github.com/geneontology/api-gorest-2021/issues/6 .

Ideally, we could figure out what the exact circumstances are for failure and not be reduced to guessing from context and timing. We'd also like to ensure that it reboots correctly when there are issues.

**Comment by kltm** [comment]
Tagging @vanaukenk

**Comment by kltm** [comment]
Exploring another failure on Sunday, can actually see an error this time:

```
[15:53:03] 'run-barista' errored after 1.92 h
[15:53:03] Error: Command `node barista.js --debug 0 --users ~/local/src/git/go-site/metadata/users.yaml --groups ~/local/src/git/go-site/metadata/groups.yaml XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX --context go --default-namespace minerva_public XXXXXXXXXXXXX` failed with exit code 
    at Socket.onChildStdout (child_process.js:334:14)
    at emitOne (events.js:121:20)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:246:13)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at Pipe.onread (net.js:601:20)
```

Three restarts were in fact actually attempted, but failed on continued aux port use by repl.

Attempted supervisor restart an hour later was successful without additional intervention.

Hm.

Reading through the supervisord docs, there does not seem to be a good back-off-while-retrying system in place (i.e. https://github.com/Supervisor/supervisor/issues/487). There seem to be two immediate choices here: try and turn off the repl (which may or may not be the actual problem if the process is dying slowly in a wrapper) or just load it with enough retries (which are slowly accumulating a slowdown) that we are able to get back up again.

As this gets explored, I'd like to start with are many more retries (30 would give about five minutes is there is no pause) and expanding the log size.

**Comment by kltm** [comment]
Doubled log sizes and `startretries` up by a factor of 10.
If there is another failure that does not autorecover for these reasons, will look into removing repl.

**Comment by kltm** [comment]
Nobody logged in, so went ahead and tried reloading. Interesting that it didn't seem to disconnect correctly, so it kept trying to restart even while the previous instance was still up. Noting that it did retry more than three times, so the new config seems to be in place. Also, the repl problem was the given error, so it seems the previous instance is present, rather than an issue directly with the repl.
May need to look harder at failures and why I seemed to be exhausting the three restarts, but when I logged in an hour after the failure there was nothing running.

**Comment by kltm** [comment]
Down again just after midnight--it did not self-recover as hoped. Diving in again.

**Comment by kltm** [comment]
I'm currently exploring that at least part of the cause may be extremely high bot/crawler traffic. I've now put robots.txt in place; will see if I can curb incoming traffic more directly as well.

**Comment by kltm** [comment]
The last two outages seem to have been proceeded by a large amount of bot/crawler traffic (although what has been normal/abnormal historically is still a little unclear). In particular, `PetalBot` and `WhatWeb` have sent thousands of requests into noctua/barista.
For noctua, noctua at bbop (legacy domain), barista, and minerva, I've put in a blanket deny robots.txt and added anti-bot stanzas to all vhosts like:
```apache2
    ## Setup robots.txt.
    DocumentRoot /var/www/html
    Alias /robots.txt /var/www/html/robots.txt
    RewriteEngine On
    RewriteRule ^/robots.txt /robots.txt

    ## Get aggressive with badly behaving bots.
    RewriteCond %{HTTP_USER_AGENT}  ^.*BOT1.*$ [OR]
    RewriteCond %{HTTP_USER_AGENT}  ^.*BOTN.*$
    RewriteRule . - [R=403,L]
```

Currently blocked bots are: Adsbot, AhrefsBot, Amazonbot, Applebot, BingBot, DotBot ,Googlebot, infotiger, MauiBot, PetalBot, semrush, WhatWeb.

**Comment by kltm** [comment]
Looks like https://github.com/bitinn/node-fetch is the GO-CAM API bit that fetches "static files" hot from barista. Releasing the block on it.

**Comment by kltm** [comment]
Devops-wise, I've removed the outer wrapper that supervisord uses for controlling barista (gulpfile run inside bash), so it's just the raw node command. This seems to work a little better and start and stop seem to behave more as expected. (Previously, that did not always seem to work.) Light testing seems to indicate no changes.

**Comment by kltm** [comment]
Summary so far:
 * recent known bots are now being filtered at the proxy and should not be able to make contact with the curatorial interfaces
 * a `robots.txt` is now in place that should tell other bots not to bother us; anything that continues to violate this will be added to the filtering list
 * the wrapper for barista has been simplified and seems to be interacting better with its manager

If this does not significantly help out, next steps could be:
* changing barista's manager to something more clear to work with, possibly monit (better recovery in case of failures)
* additional exploration of what triggers failures (should be easier with less bots and less overall traffic)
* add additional debugging code to barista (may make diagnostics easier)
* attempt to simulate the failure in a systematic way (with incoming traffic picked up from the log played back; may require another outage period)

**Comment by kltm** [comment]
While we have had (so far) no further outages, for closing this ticket, I'd like to explore playing back the logs over the problematic period in a controlled environment. I have preserved the relevant logs from the period.

**Comment by kltm** [comment]
@vanaukenk I'm tempted to close this out, as I think it's unlikely that I'll get a chance to do controlled replay experiments as 1) this no longer seems to be an immediate problem and 2) we'll be addressing this in the middle term with the GO API and GO-CAM API refactors, as well as more advanced devops that would allow for automated restarts. I think it's safe to say that too much input causes problems, even if we're not sure what specific part shuts things down, and those already have roadmapped fixes.

**Comment by kltm** [comment]
Noting that we're at about a month of no issues and that we've done some training on recovery so that getting things going again depends less on one person. More training scheduled https://github.com/geneontology/operations/issues/56

**Comment by kltm** [comment]
Well, I believe I actually have a partial answer to the question of what happens to barista in some cases. I found that using apache bench I could completely destroy an express server using apache bench with some fairly low concurrency number, like between five and ten. The question then becomes one of restarting and devops. Easy to bring down without looking for particularly dangerous queries.
